# Generated by Django 4.1.7 on 2023-04-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_hobbies_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbies',
            name='category',
            field=models.CharField(choices=[('sport', 's'), ('traveling', 't'), ('painting', 'p')], max_length=100),
        ),
    ]
