# Generated by Django 4.1.7 on 2023-04-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_alter_hobbies_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbies',
            name='category',
            field=models.CharField(choices=[('s', 'sport'), ('t', 'traveling'), ('p', 'painting')], max_length=100),
        ),
    ]
