# Generated by Django 4.1.7 on 2023-04-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_alter_hobbies_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishments',
            name='category',
            field=models.CharField(choices=[('C', 'Cafe'), ('R', 'Restaurant'), ('P', 'Pub')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='category',
            field=models.CharField(choices=[('S', 'Sport'), ('T', 'Traveling'), ('P', 'Painting')], max_length=100),
        ),
    ]
