# Generated by Django 4.1.7 on 2023-04-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_guest_host_remove_appointments_user1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishments',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='establishments',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='establishments',
            name='category',
            field=models.CharField(choices=[('C', 'Cafe'), ('R', 'Restaurant'), ('P', 'Pub')], max_length=1),
        ),
    ]
