# Generated by Django 4.1.7 on 2023-05-16 15:14

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_alter_appointments_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointments',
            options={'verbose_name': 'Свидание', 'verbose_name_plural': 'Свидания'},
        ),
        migrations.AddField(
            model_name='host',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('B', 'Busy')], default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='establishments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.establishments', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.guest', verbose_name='Приглашённый'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.host', verbose_name='Приглашающий'),
        ),
        migrations.AlterField(
            model_name='establishments',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='establishments',
            name='category',
            field=models.CharField(choices=[('C', 'Cafe'), ('R', 'Restaurant'), ('P', 'Pub')], max_length=1, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='establishments',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Предложение'),
        ),
        migrations.AlterField(
            model_name='establishments',
            name='phone',
            field=models.CharField(max_length=100, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='establishmentsrating',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='establishmentsrating',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.establishments', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='establishmentsrating',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5, message='Введите значение между 1 - 5'), django.core.validators.MinValueValidator(1, message='Введите значение между 1 - 5')], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='min_bill_value',
            field=models.PositiveIntegerField(verbose_name='Желание'),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='category',
            field=models.CharField(choices=[('S', 'Sport'), ('T', 'Traveling'), ('P', 'Painting')], max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='name_hobby',
            field=models.CharField(max_length=100, verbose_name='Название хобби'),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='user',
            field=models.ManyToManyField(to='appointment.users', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='host',
            name='max_spend_value',
            field=models.PositiveIntegerField(verbose_name='Предложение'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='date_create',
            field=models.DateTimeField(auto_created=datetime.datetime, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='passport_id',
            field=models.CharField(max_length=40, unique=True, verbose_name='Уникальный номер'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment.users', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5, message='Введите значение между 1 - 5'), django.core.validators.MinValueValidator(1, message='Введите значение между 1 - 5')], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.users', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(90, message='Is too old'), django.core.validators.MinValueValidator(18, message='Is too young')], verbose_name='Возраст'),
        ),
    ]
