# Generated by Django 4.1.7 on 2023-05-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_alter_host_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishments',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
