# Generated by Django 4.1.7 on 2023-05-16 16:49

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_alter_establishments_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(90, message='Is too old'), django.core.validators.MinValueValidator(18, message='Is too young')], verbose_name='Возраст'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(auto_created=datetime.datetime, verbose_name='Время заказа')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointments', verbose_name='Свидание')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.establishments', verbose_name='Место')),
            ],
        ),
    ]
