# Generated by Django 4.1.7 on 2023-05-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0014_alter_users_age_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='place',
        ),
    ]
