# Generated by Django 4.1.7 on 2023-05-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0015_alter_order_options_remove_order_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.CharField(max_length=100, verbose_name='Комментарий к заказу'),
        ),
    ]
