# Generated by Django 4.1.7 on 2023-06-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0018_establishments_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(verbose_name='значение')),
            ],
        ),
    ]
